name: Django Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositori
      uses: actions/checkout@v3

    - name: Instal·lar Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instal·lar unzip (si cal)
      run: sudo apt-get install unzip

    - name: Descomprimir projecte
      run: unzip Projecte_Django_Junjie_Wang.zip

    - name: Instal·lar dependències
      working-directory: Projecte_Django_Junjie_Wang
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Executar migracions
      working-directory: Projecte_Django_Junjie_Wang
      run: |
        python manage.py makemigrations
        python manage.py migrate

    - name: Executar tests unitaris
      working-directory: Projecte_Django_Junjie_Wang
      run: |
        python manage.py test
